services:
  web_front:
    build: .
    container_name: web_front
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "5173:5173"
    # networks:
    #   - note_network

volumes:
  node_modules:
